dist: xenial
compiler: gcc
sudo: required
addons:
  apt:
    packages:
    - git
    - cmake
    - ccache
    - g++

branches:
  only:
  - master

before_install:
  - sudo apt-get update -q
  - ./bldBench.sh

install:
  - mkdir build

script:
  - cd build
  - cmake ../tests
  - make; make test
